// INCLUDING A, B, C, D, E
const columnB = [
  "Agonized Anteater",
  "Abandoned Armadillo",
  "Anguished Alpaca",
  "Betrayed Badger",
  "Bitter Bison",
  "Crestfallen Cheetah",
  "Crushed Cockatoo",
  "Cynical Crab",
  "Despondent Dolphin",
  "Disillusioned Dingo",
  "Doomed Duck",
  "Embittered Eagle",
  "Evasive Eel",
  "Exiled Elephant",
  "Anxious Axolotl",
  "Bitter Bat",
  "Cold Crow",
  "Dazed Dog",
  "Empty Elk",
];

// INCLUDING F, G, H, I, J
const columnI = [
  "Forlorn Ferret",
  "Forsaken Flamingo",
  "Frustrated Frog",
  "Grieving Gecko",
  "Gloomy Goat",
  "Guarded Gnu",
  "Heartbroken Hedgehog",
  "Hopeless Hyena",
  "Hesitant Hamster",
  "Insecure Iguana",
  "Isolated Impala",
  "Irritated Ibex",
  "Jilted Jackal",
  "Joyless Jaguar",
  "Jaded Jellyfish",
  "Fading Fox",
  "Hopeless Hen",
  "Hurt Hare",
  "Ill Iguana",
  "Joyless Jackal",
];

// INCLUDING K, L, M, N, 0
const columnN = [
  "Klepto Koala",
  "Knackered Kiwi",
  "Lonely Llama",
  "Lovelorn Leopard",
  "Lamenting Lobster",
  "Melancholy Meerkat",
  "Mournful Macaw",
  "Miserable Mole",
  "Neglected Narwhal",
  "Nostalgic Newt",
  "Nervous Nightingale",
  "Overwhelmed Otter",
  "Ostracized Owl",
  "Oppressed Opossum",
  "Kicked Koala",
  "Lost Lizard",
  "Moody Mouse",
  "Offended Ox",
  "Old Otter",
];

// INCLUDING P, Q, R, S, T
const columnG = [
  "Pessimistic Penguin",
  "Panicked Puffin",
  "Paranoid Parrot",
  "Quivering Quail",
  "Quenched Quokka",
  "Questionable Quetzal",
  "Regretful Raccoon",
  "Remorseful Rhino",
  "Rejected Rabbit",
  "Sobbing Squirrel",
  "Sulking Salamander",
  "Suffering Seahorse",
  "Tragic Tortoise",
  "Tearful Tiger",
  "Tormented Tarantula",
  "Pouty Parrot",
  "Rotten Roach",
  "Sad Seal",
  "Sore Swan",
  "Tense Toad",
];

// INCLUDING U, V, W, X, Y, Z
const columnO = [
  "Unstable Urchin",
  "Upset Uakari",
  "Unloved Umbrellabird",
  "Vengeful Viper",
  "Vacant Vulture",
  "Vanquished Vervet",
  "Weeping Walrus",
  "Wistful Weasel",
  "Woeful Wombat",
  "Xenophobic Xerus",
  "Yearning Yak",
  "Yawning Yellowjacket",
  "Yelping Yabby",
  "Zonked Zebra",
  "Zesty Zebu",
  "Zealous Zorilla",
  "Weak Wolf",
];
