// INCLUDING A, B, C, D, E
const columnB = [
  "Abandoned Armadillo",
  "Agonized Anteater",
  "Anguished Alpaca",
  "Anxious Axolotl",
  "Bereaved Bat",
  "Betrayed Badger",
  "Bitter Bison",
  "Cold Crow",
  "Crestfallen Cheetah",
  "Crushed Cockatoo",
  "Cynical Crab",
  "Despondent Dolphin",
  "Disillusioned Dingo",
  "Dazed Dog",
  "Doomed Duck",
  "Empty Elk",
  "Embittered Eagle",
  "Evasive Eel",
  "Exiled Elephant",
];

// INCLUDING F, G, H, I, J
const columnI = [
  "Fading Fox",
  "Forsaken Flamingo",
  "Forlorn Ferret",
  "Frustrated Frog",
  "Grieving Gecko",
  "Gloomy Goat",
  "Guarded Gnu",
  "Haunted Hen",
  "Heartbroken Hedgehog",
  "Hopeless Hyena",
  "Hesitant Hamster",
  "Ill Iguana",
  "Insecure Inchworm",
  "Isolated Impala",
  "Irritated Ibex",
  "Jaded Jellyfish",
  "Jilted Jerboa",
  "Jinxed Jackal",
  "Joyless Jaguar",
  "Hurt Hare",
];

// INCLUDING K, L, M, N, 0
const columnN = [
  "Kicked Kakapo",
  "Klepto Koala",
  "Knackered Kiwi",
  "Lamenting Lobster",
  "Lonely Llama",
  "Lovelorn Leopard",
  "Lost Lizard",
  "Melancholy Meerkat",
  "Miserable Mole",
  "Moody Mouse",
  "Mournful Macaw",
  "Neglected Narwhal",
  "Nervous Nightingale",
  "Nostalgic Newt",
  "Offended Ox",
  "Old Orangutan",
  "Oppressed Opossum",
  "Ostracized Owl",
  "Overwhelmed Otter",
];

// INCLUDING P, Q, R, S, T
const columnG = [
  "Panicked Puffin",
  "Paranoid Pangolin",
  "Pessimistic Penguin",
  "Pouty Parrot",
  "Quenched Quokka",
  "Questionable Quetzal",
  "Quivering Quail",
  "Regretful Raccoon",
  "Rejected Rabbit",
  "Remorseful Rhino",
  "Rotten Roach",
  "Sad Seal",
  "Sobbing Squirrel",
  "Sore Swan",
  "Sulking Salamander",
  "Suffering Seahorse",
  "Tearful Tiger",
  "Tense Toad",
  "Tormented Tarantula",
  "Tragic Tortoise",
];

// INCLUDING U, V, W, X, Y, Z
const columnO = [
  "Unloved Umbrellabird",
  "Unstable Urchin",
  "Upset Uakari",
  "Vacant Vulture",
  "Vanquished Vervet",
  "Vengeful Viper",
  "Weak Wolf",
  "Weeping Walrus",
  "Wistful Weasel",
  "Woeful Wombat",
  "Xenophobic Xerus",
  "Yearning Yak",
  "Yawning Yellowjacket",
  "Yelping Yabby",
  "Zesty Zebu",
  "Zealous Zorilla",
  "Zonked Zebra",
];
